### ISSUE TITLE
when i change video num to 1, it bugs

### ISSUE THREAD

**Issue by Justinfungi** [JunyaoHu/common_metrics_on_video_quality#16]
torch.Size([1, 167, 3, 64, 64])
torch.Size([1, 167, 3, 64, 64])
<class 'torch.Tensor'>
<class 'torch.Tensor'>
styleganv
calculate_fvd...
/mnt/znzz/jus/code/Matrix/common_metrics_on_video_quality/fvd/styleganv/i3d_torchscript.pt
  0%|                                                                                  | 0/21 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/znzz/jus/code/Matrix/common_metrics_on_video_quality/demo.py", line 59, in <module>
    result['fvd'] = calculate_fvd(img1_tensor, img2_tensor, device, method='styleganv')
  File "/mnt/znzz/jus/code/Matrix/common_metrics_on_video_quality/calculate_fvd.py", line 53, in calculate_fvd
    feats1 = get_fvd_feats(videos_clip1, i3d=i3d, device=device)
  File "/mnt/znzz/jus/code/Matrix/common_metrics_on_video_quality/fvd/styleganv/fvd.py", line 34, in get_fvd_feats
    embeddings = get_feats(videos, i3d, device, bs)
  File "/mnt/znzz/jus/code/Matrix/common_metrics_on_video_quality/fvd/styleganv/fvd.py", line 27, in get_feats
    feats = np.vstack([feats, detector(torch.stack([preprocess_single(video) for video in videos[i*bs:(i+1)*bs]]).to(device), **detector_kwargs).detach().cpu().numpy()])
  File "/root/.conda/pkgs/mv_portrait_matrix/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.conda/pkgs/mv_portrait_matrix/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.conda/pkgs/mv_portrait_matrix/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 193, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/root/.conda/pkgs/mv_portrait_matrix/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 212, in parallel_apply
    return parallel_apply(
  File "/root/.conda/pkgs/mv_portrait_matrix/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 126, in parallel_apply
    output.reraise()
  File "/root/.conda/pkgs/mv_portrait_matrix/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/root/.conda/pkgs/mv_portrait_matrix/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 96, in _worker
    output = module(*input, **kwargs)
  File "/root/.conda/pkgs/mv_portrait_matrix/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.conda/pkgs/mv_portrait_matrix/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: forward() is missing value for argument 'x'. Declaration: forward(__torch__.src.i3dpt_jit.I3D self, Tensor x, bool rescale=False, bool resize=False, bool return_features=False) -> Tensor

**Comment by JunyaoHu** [comment]
This project studies the distribution of a series of videos and is not suitable for verifying the quality of a video
